name = "mirror-crm"
compatibility_date = "2024-06-20"

[site]
bucket = "public"

env = { }

[[kv_namespaces]]
binding = "CRM_KV"
id = ""
preview_id = ""

[[r2_buckets]]
binding = "CRM_FILES"
bucket_name = "mirror-crm-files"

[vars]
SESSION_COOKIE_NAME = "mirrorsid"
SESSION_TTL_SECONDS = 60 * 60 * 24 * 7 # 7 days

[observability]
enabled = true
