name = "mirror-crm"
compatibility_date = "2024-06-20"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "CRM_KV"
id = "mirror-crm-kv"
preview_id = "mirror-crm-kv-preview"

[[r2_buckets]]
binding = "CRM_FILES"
bucket_name = "mirror-crm-files"

[vars]
SESSION_COOKIE_NAME = "mirrorsid"
SESSION_TTL_SECONDS = 604800 # 7 days

[observability]
enabled = true
